### ISSUE TITLE
Retries for send_notification and push registration

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/va-enp-api#43]
## User Story - Business Need
The `send_notification` method is intended to send email, sms, and push. We want that method to retry in the event of a provider retryable exception. We also want one-off methods to retry when applicable, such as the push registration.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** service using VA Notify
**I want** to know my messages will be retried in the event there is a temporary problem
**So that** I am confident my messages will reach Veteran devices

### Additional Info and Resources

- Tenacity [docs](https://tenacity.readthedocs.io/en/latest/)
- Tenacity [repository](https://github.com/jd/tenacity)

## Acceptance Criteria

- [x] Tenacity added as a dependency
- [x] `send_notification` method in the `ProviderBase` class utilizes retry functionality
- [x] Push registration is retried using tenacity
- [x] `stop` conditions are defined separately from the method, and used in the `retry` decorator
- [x] `wait` conditions are defined separately from the method, and used in the `retry` decorator
- [x] `retry` condition only triggers if a provider retryable exception occurs
- [x] This work is added to the sprint review slide deck (key win bullet point and demo slide)

**Comment by EvanParish** [comment]
I have done some learning with tenacity by reading the docs and experimenting with it in the repo. I may need to change my approach so far to account for the async nature of our application. I'm looking into using tenacity in an async manner today.

**Comment by EvanParish** [comment]
I continue to experiment with tenacity. I'm trying to understand if using `AsyncRetrying` is actually necessary. According to the [tenacity docs](https://tenacity.readthedocs.io/en/latest/#async-and-retry) the `@retry` decorator should work for async functions and I'm seeing that in my testing. I guess the main question is how we want to handle exceptions, which may be a question to be formally answered later.

**Comment by EvanParish** [comment]
Unit testing proved more difficult than I expected. I wasn't able to write tests to check for retrying specifically, but I did a lot of testing to verify they are happening as expected. Depending on how much more time we want to spend on this I could work with someone to see if a fresh set of eyes could help with the situation.

This will be rolling over because working with new technology always comes with a learning curve and that just took a little longer than expected this time. The PR is ready for review unless we want to write more unit tests. I'll verify in the morning what direction we want to take.

**Comment by EvanParish** [comment]
The PR is open, just waiting on reviews. This ticket will be closed tomorrow.
